### ISSUE TITLE
Attempting to Inference on a CPU only machine fails

### ISSUE THREAD

**Issue by sauraedron** [fastestimator/fastestimator#1103]
Experimenting with Fast Estimator.

I had trained a model using FE on a GPU instance(sagemaker). 

I downloaded the saved .pt file and I am trying to create a python file for inferencing. The code is based on the Unet example on the Fastestimator site.

Since my laptop is CPU only, I am using the cpu docker image ( fastestimator/fastestimator:nightly-cpu).
I get the following error:
`RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.`

for 
```python
model = fe.build(model_fn=lambda: UNet(input_size=(1, 512, 512)),
                            optimizer_fn=lambda x: torch.optim.Adam(params=x, lr=0.0001),
                            model_name="model_name",
                            weights_path=weights_path)
```

Could you let me know if I am missing anything ?

**Comment by vbvg2008** [comment]
Thanks for filing the issue! 

I have reproduced the problem and filed a PR to fix this problem. 

After merging the PR, you can use the master branch's code do the inferencing without problem.  To install the master branch directly, you can do `pip install git+https://github.com/fastestimator/fastestimator.git` inside the container. 

Or you can wait until next day after our nightly test finishes the nightly deployment, then you can pull `fastestimator/fastestimator:nightly-cpu` and use it without problem

**Comment by sauraedron** [comment]
That was fast. :)
As a hack i did the same modification in the library inside the container.

**Comment by vbvg2008** [comment]
cool! let me know if there's any further problem
