### ISSUE TITLE
deactivate

### ISSUE THREAD

**Issue by saramoira** [fastestimator/fastestimator#1233]

**Comment by TortoiseHam** [comment]
Hi @saramoira, could you elaborate on what it is you think should be deactivated?

**Comment by saramoira** [comment]
My apologies, I'm not sure why that comment was sent. My best guess is an accidental window change when I was typing elsewhere. Very strange.

**Comment by TortoiseHam** [comment]
No worries, if you ever have any requests for this repo just let us know :)
