### ISSUE TITLE
question about key filtering/ value filtering with CSVDataset class

### ISSUE THREAD

**Issue by lzl199704** [fastestimator/fastestimator#1305]
Hi,

I am wondering is there a way to filter CSVDataset class by keyword or value?

Best regards

Zelong

**Comment by TortoiseHam** [comment]
Hi Zelong,

We don't have that in the CSVDataset class at the moment, but we can definitely look into it. Are you looking for exact value matching (something like `excludeif={'key':['bad1', 'bad2']}` ) or do you need regex/range comprehension (`excludeif={'key': > 53}` ). 

In the meantime there are a few workarounds. One would be the RemoveIf NumpyOp, which you could add to your pipeline. Also, if you happen to know the row indices you want to get rid of ahead of time, you could use the skiprows argument in the CSV dataset constructor (it's one of the kwarg arguments that we pass through to [pandas](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html))

**Comment by lzl199704** [comment]
Hi Michael,

I would like to use a feature to select a particular feature, for example,
includeif = ('key': ['train'])

Best regards

Zelong

**Comment by TortoiseHam** [comment]
Hi Zelong, 

This [PR](https://github.com/fastestimator/fastestimator/pull/1306) adds the filtering feature. If you pull the latest you can give it a try and let us know whether it'll work for you. In addition to the dictionary style limits we also support a more expressive lambda function filtering if you need it.

**Comment by vbvg2008** [comment]
Closing this issue as the PR is merged and feature supported.  Feel free to open it if there are additional request.
