### ISSUE TITLE
Improper use of cpu_count() for spawning sub processes

### ISSUE THREAD

**Issue by dibya-pati** [fastestimator/fastestimator#14]
![image](https://user-images.githubusercontent.com/32309221/59324639-98e98500-8c94-11e9-8db3-1b359e6c7cd7.png)
 
Use of multiprocessing.cpu_count() leads to inconsistent/unexpected results(slowdown) as .cpu_count() returns the total CPU's in the system and doesn't guarantee that the sub processes created will get allocated to the available CPU's. 
There are two ways to handle this:

1. Create a pool of sub processes using multiprocessing. pool(), and use/reuse the processes using .map()
2. Use os.sched_getaffinity(0) to get the actual count of processors that could be used by the parent proc for spawning sub processes

The current implementation is known to have failed and produce inconsistent results on different OS platforms/architectures

Link to issues when cpu_count() is used instead of actually cpu affinity
https://bugs.python.org/issue23530

**Comment by vbvg2008** [comment]
The ‘cpu count’ is used for two purposes:

1: it is used to configure tensorflow dataset parallel reads and parallel function mapping.   using that variable in tf.dataset should be fine, as it is suggested in official tensorflow docs.

2.it is used to create number of subprocess in the pool for ‘TFRecorder’.  I guess this part may be most relevant to the concern you raised.  

 Further investigation is needed, could you give us one failure case?

**Comment by dibya-pati** [comment]
This behavior is non-deterministic, Hence , difficult to recreate. But this has been extensively discussed/debated in the python bugs page in my first comment. As cpu_count() and sched_getaffinity() serve two distinct functionalities 

1. Thats correct. You might want to look into this issue if you are running <r1.13 https://github.com/tensorflow/tensorflow/issues/19945 and  https://github.com/tensorflow/tensorflow/releases,
2. In the code, I believe its only used to just get a count of processors as I didnt see any thread Pool getting created using multiprocessing.Pool()
